### ISSUE TITLE
Tutorial: Albedo AVIRIS-NG

### ISSUE THREAD

**Issue by scottyhq** [uwhackweek/schedule-2024#19]
**Lead:** Anton Surunis, Brent Wilder
**Date:** 21/08/2024
**Start Time:** 1045
**Duration:** 45
**Description:** All about Albedo

<details><summary>Details</summary>
<p>

### Learning Outcomes

* outcome1
* outcome2
* outcome3

### Technical Needs (GPUs? Large file storage? Unique libraries?)

</p>
</details>

**Comment by jomey** [comment]
This will have a contribution to the notebook but no in-person tutorial
