### ISSUE TITLE
Optional: impromptu tutorials

### ISSUE THREAD

**Issue by scottyhq** [uwhackweek/schedule-2024#24]
**Lead:** Awesome People
**Date:** 22/08/2024
**Start Time:** 0945
**Duration:** 45
**Description:** Things not in the original schedule worth sharing based on interest

<details><summary>Details</summary>
<p>

### Learning Outcomes

* outcome1
* outcome2
* outcome3

### Technical Needs (GPUs? Large file storage? Unique libraries?)

</p>
</details>

**Comment by JessicaS11** [comment]
Closing this as a specific schedule slot in favor of during-the-event impromptu tutorial scheduling as needs are identified.
